### ISSUE TITLE
[Bug]: database locked after validating schema

### ISSUE THREAD

**Issue by wvangerwen** [nens/threedi-schema#22]
### Contact Details

w.vangerwen@hhnk.nl

### Complexity

moderate

### Priority

low prio

### What happened?

cannot remove sqlite after validating schema. It will lock the file until notebook closed, and even then it might still be locked.

### How to Reproduce?

```import os
from threedi_schema import ThreediDatabase, errors

filename = r"E:\github\wvangerwen\hhnk-threedi-tools\tests\data\model_test\test_migration2.sqlite"

threedi_db=ThreediDatabase(filename)
threedi_db.get_session()

schema = threedi_db.schema
try:
    schema.validate_schema()
except errors.MigrationMissingError:
    pass

threedi_db = None
schema = None

os.remove(filename)
```

### What did you expect and what was the actual result?

error. see log output.

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.

### Relevant log output

```shell
PermissionError                           Traceback (most recent call last)
[e:\github\wvangerwen\hhnk-threedi-tools\hhnk_threedi_tools\core\migrate_schematisation.py](file:///E:/github/wvangerwen/hhnk-threedi-tools/hhnk_threedi_tools/core/migrate_schematisation.py) in line 19
     [160](file:///e%3A/github/wvangerwen/hhnk-threedi-tools/hhnk_threedi_tools/core/migrate_schematisation.py?line=159) threedi_db = None
     [161](file:///e%3A/github/wvangerwen/hhnk-threedi-tools/hhnk_threedi_tools/core/migrate_schematisation.py?line=160) schema = None
---> [163](file:///e%3A/github/wvangerwen/hhnk-threedi-tools/hhnk_threedi_tools/core/migrate_schematisation.py?line=162) os.remove(filename)

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process:
```

### Additional info

Anything else you would like to share?

**Comment by caspervdw** [comment]
@benvanbasten-ns can you reproduce this on Windows

**Comment by caspervdw** [comment]
Thanks for the report @wvangerwen  we confirmed that it is there (on Windows only, hence the reply of @elisallenens).

The root cause is that the database connection is not closed. This is because SQLAlchemy pools database connections by default. We are considering to not pool the connections, but in that case we need to confirm that the modelchecker performance doesn't deteriorate.

A quickfix (workaround) for you now is calling `threedi_db.engine.dispose()` before removing.
