### ISSUE TITLE
Variable friction and 1D vegetation parameters

### ISSUE THREAD

**Issue by GolnesaK** [nens/threedi-schema#42]
For context, please read the epic description: https://app.zenhub.com/workspaces/team-3di-5ef60eff1973dd0024268b90/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTYwNDA3

Users will need to be able to specify multiple friction and vegetation parameters across the cross-section (i.e., one for each segment).

Suggested implementation is to add the following fields to the table `v2_cross_section_location`

- friction_values (notice the plural; the singular `friction_value` already exists and applies to the whole cross-section)
- vegetation_stem_density (float)
- vegetation_stem_densities (string containing space-separated floats)
- vegetation_stem_diameter (float)
- vegetation_stem_diameters (string containing space-separated floats)
- vegetation_height (float)
- vegetation_heights (string containing space-separated floats)
- vegetation_drag_coefficient (float)
- vegetation_drag_coefficients (string containing space-separated floats)

**Comment by leendertvanwolfswinkel** [comment]
@margrietpalm I made a small correction: values should be space-separated instead of comma-separated

**Comment by GolnesaK** [comment]
Correction: The "plural" parameters introduced above must be defined in "v2_cross_section_definition" table

**Comment by margrietpalm** [comment]
> Correction: The "plural" parameters introduced above must be defined in "v2_cross_section_definition" table

@GolnesaK I've changed this in commit: https://github.com/nens/threedi-schema/pull/50/commits/bc51003b947d3fcef0c393ecf86a59c545d102a0

**Comment by daanvaningen** [comment]
api is still on 0.217.13
