### ISSUE TITLE
Multiple roughness/friction coefficient

### ISSUE THREAD

**Issue by GolnesaK** [nens/threedi-schema#43]
Please read the epic description first: https://app.zenhub.com/workspaces/team-3di-5ef60eff1973dd0024268b90/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTYwNDA3

- [ ] Allow users to define multiple roughness/friction coefficients (one for each segment) for both Chézy and Manning, only for open YZ profiles

I think the most straightforward way to implement this is to add a column `friction_values` (plural) to `v2_cross_section_location`, containing a space-separated list of floats of the same length as the list of `width`s.

If a user fills in both `friction_value` (singular) and `friction_values` (plural), the `friction_value` should be ignored and only `friction_values` used

**Comment by elisalle** [comment]
> If a user fills in both `friction_value` (singular) and `friction_values` (plural), the `friction_value` should be ignored and only `friction_values` used
The main issue I see with this is that there are already several checks which use `friction_value`. Should all those checks be rewritten?
Perhaps it would be better to add a check which gives an ERROR when both `friction_value` and `friction_values` are filled in.

**Comment by GolnesaK** [comment]
Can we have a meeting about this too?

**Comment by leendertvanwolfswinkel** [comment]
merged this ticket with #42
