### ISSUE TITLE
Migrate to geopackage

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schema#45]
Make a function that moves all the data from spatialite to geopackage. The schema itself can stay the same (insofar possible, e.g. multiple geometry columns on one table are not supported). Views are not supported by GeoPackage, so functionality related to views can be removed.

At this stage, this will be for development/testing purposes only, so take this into account w.r.t. release

**Comment by margrietpalm** [comment]
Is there a source for this statement?

> Views are not supported by GeoPackage, so functionality related to views can be removed

Because I haven't been able find any source. I did find [this issue](https://issues.qgis.org/issues/18026) with views, but there seems to be a workaround.

Also, do the views not serve a purpose? And thus cannot be just removed.

**Comment by margrietpalm** [comment]
Ran tests for hydxlib with geopackage and everything runs fine. For some reason I cannot open https://app.zenhub.com/workspaces/team-3di-5ef60eff1973dd0024268b90/issues/gh/nens/hydxlib/55 to mention this there.
