### ISSUE TITLE
Inflow schema 300 (threedi-schema)

### ISSUE THREAD

**Issue by margrietpalm** [nens/threedi-schema#65]
- [ ] Schema changes according to this Excel sheet: https://nelenschuurmans.sharepoint.com/:x:/s/IT/EQGeF_5W-GZNvDB-pVt5b4UBs0zFsMxNhOOxIKrKOsVIuQ?e=ZZQwTO
- [ ] Define migration

Non-trivial parts of the migration:

<img width="1336" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk1vQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a391a89d4e27a90a1076cb73da9e114a1822ba79/inflow_tables.drawio.png" alt="inflow_tables.drawio.png" />

**Comment by leendertvanwolfswinkel** [comment]
**dry_weather_flow**
- [ ] dry_weather_flow_distribution_id is NULL; this should be 1. Also, we should test if changing the dry_weather_flow_distribution is picked up correctly by the simulation template worker
- [ ] interpolate is NULL. this should be true or false (I don't know what the default is, please deduce from  what the template worker does)

**surface_map**
- [ ] all features have the same geometry

**Comment by margrietpalm** [comment]
Reproduced issue and it seems that I actually completely forgot setting these geometries. Most likely a remnant of the changes in setting up the geometry columns. Shouldn't be too hard to fix; but geometry columns are never easy.
