### ISSUE TITLE
Spatialite with schema version 214 still contains NOT NULL constraints

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schema#9]
In schema version 214 (current production version), the global settings table still contains NOT NULL constraints. If the 3Di Schematisation Editor attempts to export to spatialite with `output_time_step = NULL`, the following error is produced:

![image](https://user-images.githubusercontent.com/26224299/225728445-b9bb6a91-81c0-4e78-a110-21584c100c12.png)

A look at the schema of `v2_global_settings` shows that the following fields still have NOT NULL constraints:
- output_time_step
- frict_type
- minimum_sim_time_step
- frict_avg
- use_0d_inflow

In `v2_aggregation_settings`:
- aggregation_method

In `v2_control`:
- control_type

In `v2_control_measure_map`:
- object_type
- object_id
- weight

In `v2_control_memory`:
- measure_variable
- action_type
- action_value
- target_type
- target_id

In `v2_control_table`:
- action_table
- action_type
- measure_variable
- target_type
- target_id

To make sure I have a 'normal' spatialite, I downloaded
[this old spatialite](https://github.com/nens/threedi-schema/files/10995120/hab_til_hab_1d2d_Sce3_AsVig_NOT_MIGRATED.zip)
and migrated it using `threedi-schema 0.214.4`. After migration, I still see these NOT NULL constraints.

**Comment by caspervdw** [comment]
Existing constraints are not cleaned up as far as I remember. Only for new  (or changed?) tables are guaranteed to have no constraints. So this is behaviour I would expect.

Maybe good to make a method that cleans constraints? Like the “set_views”.
