### ISSUE TITLE
Migration causes DatabaseError for this specific sqlite

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schema#94]
`threedi-schema` version: 0.226.1

Sqlite: [basis_Hoofdgebied_integraal.zip](https://github.com/user-attachments/files/17015426/basis_Hoofdgebied_integraal.zip)

Error: `DatabaseError('(sqlite3.DatabaseError) malformed database schema (v2_impervious_surface) - table v2_impervious_surface already exists')`

**Comment by margrietpalm** [comment]
@leendertvanwolfswinkel I cannot reproduce this with just upgrading using the latest threedi-schema (0.226.4). Under what exact conditions does this happen?
