### ISSUE TITLE
Remove measure_variable from memory_control and table_control

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schema#97]
In the spreadsheet for the structure control migration, the attribute "measure_variable" is used 3 times:

- In `control_measure_location`, as a new attribute, filled with value 'water_level'
- In `memory_control`, migrated from `v2_control_memory.measure_variable`
- In `table_control`, migrated from `v2_control_table.measure_variable`

This was a mistake; what it should be is:
- In `control_measure_location`, the attribute `measure_variable` is to be filled with the value `water_level` (which is already the case in the current implementation)
- `memory_control` should not have an attribute `measure_variable`
- `table_control` should not have an attribute `measure_variable`
 
If I am not mistaken, the template worker only uses `control_measure_location.measure_variable`, so no changes in the template worker are required in that case

**Comment by margrietpalm** [comment]
Also requires API changes: https://app.zenhub.com/workspaces/team-3di-5ef60eff1973dd0024268b90/issues/gh/nens/threedi-api/2322

**Comment by margrietpalm** [comment]
Currently implemented as hotfix for 224. But work on released API may be more complicated, so maybe consider releasing this as seperate migration.

**Comment by margrietpalm** [comment]
Hmm, I find this very confusing. Linking the variable to the location, but the other parameters to the ControlTable or ControlMemory. So for example, the threshold for memory control is set in ControlMemory, but the actual variable it is linked to is linked to the location. However, without knowing the variable, a value like threshold makes no sense. 

Also, this seems to require a lot of work in the template worker.

**Comment by margrietpalm** [comment]
Rename:
* control_measure_map -> measure_map
* control_measure_location -> measure_location

**Comment by margrietpalm** [comment]
Seperate migration (227?)

**Comment by margrietpalm** [comment]
In schema `ControlMeasureMap` and `ControlMeasureLocation` are still used, maybe rename those as well
